name: Build DEB

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies (Fix ldid error)
        run: |
          # 这就是刚才缺少的“车钥匙”！
          # 安装 ldid 签名工具
          brew install ldid
          
      - name: Install Theos
        run: |
          # 手动克隆 Theos
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Get iOS SDK
        run: |
          # 暴力清理
          rm -rf $HOME/theos/sdks
          mkdir -p $HOME/theos/sdks
          
          # 克隆 SDK
          git clone --depth 1 https://github.com/xybp888/iOS-SDKs.git $HOME/theos/sdks/temp
          
          # 移动文件
          mv $HOME/theos/sdks/temp/iPhoneOS14.5.sdk $HOME/theos/sdks/iPhoneOS.sdk
          rm -rf $HOME/theos/sdks/temp

      - name: Build Package
        run: |
          # 编译！
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WeChatMod-Rootless
          path: packages/*.deb
