name: Build DEB

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Get iOS SDK
        run: |
          # 暴力删除旧文件，防止冲突
          rm -rf $HOME/theos/sdks
          # 下载 SDK
          git clone --depth 1 https://github.com/xybp888/iOS-SDKs $HOME/theos/sdks/
          # 改名
          mv $HOME/theos/sdks/iPhoneOS16.5.sdk $HOME/theos/sdks/iPhoneOS.sdk

      - name: Build Package
        run: |
          # 编译指令
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WeChatMod-Rootless
          path: packages/*.deb
